FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app

ENV NTC_LIVE_CAPTIONS_HOST=0.0.0.0
ENV NTC_LIVE_CAPTIONS_PORT=1975

CMD ["gunicorn", "-w", "1", "--threads", "4", "-b", "0.0.0.0:1975", "ntc_live_captions_app:app"]
